yum install MariaDB-server

- name: Install the MaiaDB-erver
  yum:
    name: MariaDB-server
    state: latest
	
systemctl enable mariadb.service
- name: enable mariadb service
systemd:
    name: mariadb
    enabled: yes
    
systemctl restart maraidb.service	
- name: start mariadb service
systemd:
   name: mariadb
   state: started
   
   
mysql:

CREATE USER 'admin'@'%' IDENTIFIED BY 'admin123';
- name : create admin user with password
mysql_user:
    name: "{{DB_USER}}"
	password: "{{DB_PASSWORD}}"
    host: localhost
	priv: '*.*:ALL'
    state: present  
	
create database dvsdevops;
- name: create database
mysql_db:
    name: "{{DB_NAME}}"
    state: present	
	
- name: Installing dependent packages
  command: mazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2

- name: installing apache
  yum: 
   name: httpd
   state: latest

- name: enable apache at boot time
  systemd:
    enabled: yes
    name: httpd

- name: starting  apache
  systemd:
   state: started
   name: httpd

- name: Download latest wordpress application
  get_url: 
    url: https://wordpress.org/latest.tar.gz 
    dest: /tmp/wordpress.tar.gz
    mode: '0440'
	
- name: Untar wordpress application
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/wordpress

- name: configuring wp-config.php file
  template:
    src: wp-config.php
    dest: /var/www/html/
  notify: apache restart

- name: aligning application permission
  file: path=/var/www state=directory recurse=yes owner=apache group=apache mode="0755"
  notify: apache restart
