---

- name: Installing apache
  hosts: all
  tasks:
     - name: collecting server public ip
       uri:
          url: http://169.254.169.254/latest/meta-data/public-ipv4
               return_content: yes
       register: myip

     - set_fact: public= "{{myip.content}}"

     - name: Install the latest version of Apache
       yum:
         name: httpd
         state: latest
     - name: Enable service httpd at boot time
       systemd:
          name: httpd
          enabled: yes

     - name: modifying httpd.conf file
       replace:
          path: /etc/httpd/conf/httpd.conf
          regexp: '^#ServerName www.example.com'
          replace: 'ServerName {{public}}'

     - name: copying index.html
       copy:
         src: index.html
         dest: /var/www/html
       notify: apache restart

  handlers:
     - name: apache restart
       systemd:
         state: started
         name: httpd

    

